### ISSUE TITLE
Automation of basic training series?

### ISSUE THREAD

**Issue by hagbardc** [IndivisibleOnline/Indivisible-Plugin#19]
Can we automate basic training series?

Needs information:  What?

**Comment by imlindaryan** [comment]
@hagbardc can you pls clarify?  Beyond the videos?  thx

**Comment by hagbardc** [comment]
I don't know - this was a line item that was transferred from the original Google Doc.  I didn't know what it meant back then, and I still don't :)

If you don't either, we can close it out.

**Comment by imlindaryan** [comment]
Thx!
