### ISSUE TITLE
Join Astorino (and all) topic group failed

### ISSUE THREAD

**Issue by gtrueman** [IndivisibleOnline/Indivisible-Plugin#32]
Same as #29? Click on JOIN GROUP button on http://www.indivisiblewestchester.org/astorino-group-page/ generates this error message: "there was an error. Sorry"

We should fix this and edit the error message to communicate better and more grammatically! ;)

While logged in, I tested other topic groups that are tiled on this page: http://www.indivisiblewestchester.org/mygroups/ with same result.

**Comment by howardstevens** [comment]
Resolved
