### ISSUE TITLE
Missing return navigation on local group post detail page

### ISSUE THREAD

**Issue by gtrueman** [IndivisibleOnline/Indivisible-Plugin#35]
See http://www.indivisiblewestchester.org/gastorino/

Users need some path back to the Blastorino! home page. If the right sidebar navigation was complete and hierarchical (Blastorino above and any sub pages indicated by indents or etc) then users could navigate back. As is, there is only the name of the current page in the right nav.

**Comment by howardstevens** [comment]
This is now done,
