### ISSUE TITLE
Public Events Require Login

### ISSUE THREAD

**Issue by ksnyder-mtm** [IndivisibleOnline/Indivisible-Plugin#49]
A few of the events that are tagged Public are forcing a login.
Expected behavior - someone not logged into the website is able to view. 

Bug may be related to event being tagged as a local group event, then not being visible to the public.

Examples of public events where this is happening:
Westchester Social Forum
Which Side are You on Jeff Klein?

**Comment by imlindaryan** [comment]
Will test and report if this issue is persistent.

**Comment by ksnyder-mtm** [comment]
@imlindaryan -- Did this get resolved?

**Comment by imlindaryan** [comment]
@iwksnyder hard to say - I do not see the issue as persistent in the current batch of events so we can close this

**Comment by ksnyder-mtm** [comment]
Closing as this issue has been resolved.
