### ISSUE TITLE
Local group leaders should only be able to see/approve members for their group

### ISSUE THREAD

**Issue by hagbardc** [IndivisibleOnline/Indivisible-Plugin#6]
Right now when a group leader goes to the 'Approve member' option, they see a list of all the members waiting for approval.  They should only have access / ability to view and approve members waiting to get into *their* group.

Needs Information:  Is this a correct description of the problem?

**Comment by howardstevens** [comment]
Last I tested, it correctly filtered the user list for the group leader. Who (and when) was this issue reported?

**Comment by ksnyder-mtm** [comment]
This does appear to be working for the Group Leader. Closing.
